-- Kyoty Supabase Schema
-- This script sets up the tables and basic RLS policies in Supabase.

-- 1. Cities Table
CREATE TABLE IF NOT EXISTS cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    state TEXT,
    slug TEXT NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Users Table (Linked to auth.users)
CREATE TABLE IF NOT EXISTS kyoty_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'participant', -- participant, community_admin, admin, kyoty_admin
    default_city_id BIGINT REFERENCES cities(id),
    verification_status TEXT DEFAULT 'pending',
    social_proof_type TEXT, -- linkedin, instagram
    social_proof_link TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Communities Table
CREATE TABLE IF NOT EXISTS communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    category TEXT,
    city_id BIGINT REFERENCES cities(id) ON DELETE CASCADE,
    is_travel BOOLEAN DEFAULT FALSE,
    visibility TEXT DEFAULT 'public',
    organizer_id BIGINT REFERENCES kyoty_users(id) ON DELETE SET NULL,
    rating_avg DECIMAL(2,1) DEFAULT 0,
    rating_count INTEGER DEFAULT 0,
    member_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending', -- active, pending, approved, rejected, disabled
    cover_image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Community Members Table
CREATE TABLE IF NOT EXISTS community_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT REFERENCES communities(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES kyoty_users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    approved_by BIGINT REFERENCES kyoty_users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(community_id, user_id)
);

-- 5. Events Table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT REFERENCES communities(id) ON DELETE CASCADE,
    city_id BIGINT REFERENCES cities(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    location_text TEXT,
    max_participants INTEGER,
    registered_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending', -- draft, pending, approved, rejected, open, full, completed, cancelled
    pricing_model TEXT DEFAULT 'free',
    price_per_person INTEGER,
    total_fixed_cost INTEGER,
    per_person_estimate INTEGER,
    is_paid BOOLEAN DEFAULT FALSE,
    created_by BIGINT REFERENCES kyoty_users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Event Participants Table
CREATE TABLE IF NOT EXISTS event_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES kyoty_users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'registered', -- registered, waitlisted, cancelled, removed
    waitlist_position INTEGER,
    checked_in_at TIMESTAMPTZ,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(event_id, user_id)
);

-- 7. Ticket Tiers Table
CREATE TABLE IF NOT EXISTS ticket_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    price INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    community_id BIGINT REFERENCES communities(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES kyoty_users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(event_id, user_id)
);

-- 9. Reports Table
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT REFERENCES kyoty_users(id) ON DELETE CASCADE,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'pending', -- pending, resolved
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES kyoty_users(id) ON DELETE CASCADE,
    type TEXT DEFAULT 'general',
    title TEXT NOT NULL,
    body TEXT,
    link TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Admin Logs Table
CREATE TABLE IF NOT EXISTS admin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES kyoty_users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --- RLS POLICIES ---

-- Enable RLS on all tables
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE kyoty_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;

-- 1. Cities: Public read
CREATE POLICY "Public read cities" ON cities FOR SELECT USING (true);

-- 2. Users: Public read for basic info, own profile write
CREATE POLICY "Public read users" ON kyoty_users FOR SELECT USING (true);
CREATE POLICY "User update own profile" ON kyoty_users FOR UPDATE USING (auth.uid() = auth_id);

-- 3. Communities: Public read for approved, admin write
CREATE POLICY "Public read approved communities" ON communities FOR SELECT USING (status = 'active' OR status = 'approved');
CREATE POLICY "Organizer manage own community" ON communities FOR ALL USING (organizer_id IN (SELECT id FROM kyoty_users WHERE auth_id = auth.uid()));

-- 4. Events: Public read for open/approved, organizer manage
CREATE POLICY "Public read open events" ON events FOR SELECT USING (status IN ('approved', 'open', 'full', 'completed'));
CREATE POLICY "Organizer manage own events" ON events FOR ALL USING (created_by IN (SELECT id FROM kyoty_users WHERE auth_id = auth.uid()));

-- 5. Event Participants: Own record manage
CREATE POLICY "User manage own participation" ON event_participants FOR ALL USING (user_id IN (SELECT id FROM kyoty_users WHERE auth_id = auth.uid()));

-- 6. Notifications: Own notifications manage
CREATE POLICY "User manage own notifications" ON notifications FOR ALL USING (user_id IN (SELECT id FROM kyoty_users WHERE auth_id = auth.uid()));

-- 7. Reviews: User create own review
CREATE POLICY "User manage own reviews" ON reviews FOR ALL USING (user_id IN (SELECT id FROM kyoty_users WHERE auth_id = auth.uid()));

-- 8. Reports: User create report
CREATE POLICY "User create reports" ON reports FOR INSERT WITH CHECK (reporter_id IN (SELECT id FROM kyoty_users WHERE auth_id = auth.uid()));

-- Admin bypass (simplified for MVP)
-- In a real app, you'd add policies where role = 'admin' or 'kyoty_admin' allows more access.
