-- Migration 004: Audit Fixes (Social Proof & Ticket Tiers)

-- 1. Add Social Proof fields to Users table
ALTER TABLE public.kyoty_users
ADD COLUMN social_proof_type TEXT, -- e.g. 'linkedin' or 'instagram'
ADD COLUMN social_proof_link TEXT;

-- 2. Create Ticket Tiers table for Events
CREATE TABLE IF NOT EXISTS public.ticket_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    capacity INT NOT NULL,
    price INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (if configured globally)
ALTER TABLE public.ticket_tiers ENABLE ROW LEVEL SECURITY;

-- Allow public read
CREATE POLICY "Allow public read for ticket tiers"
ON public.ticket_tiers
FOR SELECT
TO public
USING (true);

-- Allow authenticated users to insert/update (backend will enforce via server actions)
CREATE POLICY "Allow authenticated insert/update"
ON public.ticket_tiers
FOR ALL
TO authenticated
USING (true);
