-- Migration 015: Payments table for Razorpay integration
-- Tracks every captured payment. razorpay_payment_id is UNIQUE to ensure
-- idempotency — duplicate webhook deliveries are a no-op (INSERT ... ON CONFLICT DO NOTHING).

CREATE TABLE IF NOT EXISTS payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razorpay_order_id   TEXT NOT NULL,
    razorpay_payment_id TEXT NOT NULL UNIQUE,  -- idempotency key
    event_id            BIGINT REFERENCES events(id) ON DELETE SET NULL,
    user_id             BIGINT REFERENCES kyoty_users(id) ON DELETE SET NULL,
    ticket_tier_id      BIGINT REFERENCES ticket_tiers(id) ON DELETE SET NULL,
    amount_paise        INTEGER NOT NULL,       -- amount in paise (smallest INR unit)
    currency            TEXT NOT NULL DEFAULT 'INR',
    status              TEXT NOT NULL DEFAULT 'captured', -- captured | refunded | failed
    webhook_event       TEXT NOT NULL,          -- raw event name from Razorpay (e.g. 'payment.captured')
    raw_payload         JSONB,                  -- full payment entity for debugging
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Index for looking up payments by event
CREATE INDEX IF NOT EXISTS idx_payments_event_id ON payments(event_id);

-- Index for looking up payments by user
CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments(user_id);

-- RLS: only authenticated users can see their own payments; admins see all.
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own payments"
    ON payments FOR SELECT
    USING (
        user_id IN (
            SELECT id FROM kyoty_users WHERE auth_id = auth.uid()
        )
    );

CREATE POLICY "Admins can view all payments"
    ON payments FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM kyoty_users
            WHERE auth_id = auth.uid()
              AND role IN ('admin', 'kyoty_admin')
        )
    );

-- Service role (used by server actions / webhooks) bypasses RLS automatically.
